### ISSUE TITLE
Remember the links entered before

### ISSUE THREAD

**Issue by MyNameIsTroll** [dsymbol/yt-dlp-gui#1]
Wow, I am the first to create a issue :) 

I noticed that when I close the software, it does not remember the links I entered before.
For example if I add a lot of links and I don't have time to download them all but I would like to resume the download another day. 

Thank you very much for making this interface.

**Comment by dsymbol** [comment]
I'm glad you're enjoying it, 
I can make a history folder containing finished/unfinished downloads by date and time for now if you'd like. 
Currently I don't have time to create an import feature which imports that list as a whole as it'd require a full GUI change.
Let me know if that'd help.

**Comment by MyNameIsTroll** [comment]
No need to do it only for me, it doesn't matter.^^ 
Don't worry, it was just an interesting feature. Maybe other contributors will have time to do it, unfortunately I don't know much about programming to help you.
