### ISSUE TITLE
Issues launching executable

### ISSUE THREAD

**Issue by Colette-Pitamba** [dsymbol/yt-dlp-gui#10]
Machine: Mac Catalina 10.15.7
`python --version` returns 3.10.1

Running `chmod +x ./dist/yt-dlp-gui` on mac doesn't do anything. Is there another step in this installation process?

**Comment by dsymbol** [comment]
Building on Mac is untested, I see that you're giving it execution permissions but did you actually try running it? `./yt-dlp-gui`
I'd recommend updating the code with `git pull` before doing the above.
