### ISSUE TITLE
Shows error even when works correctly

### ISSUE THREAD

**Issue by Groonir** [dsymbol/yt-dlp-gui#11]
**How to reproduce:**
1. Open the gui
2. Add link 
3. Set format to wav
4. download

**What happens**
Shows ERROR on Progress, Size, Status and speed.

but file is saved correctly.

![image](https://user-images.githubusercontent.com/124251277/236632599-d2dd1249-d426-4e92-8a3c-1273a10f322b.png)

**Comment by dsymbol** [comment]
Could you please provide the relevant portion of the debug.log file located in the root directory of the program

**Comment by Groonir** [comment]
[debug.log](https://github.com/dsymbol/yt-dlp-gui/files/11414340/debug.log)

I have tried using it on sites that dont support it so there could be an error logged because of that

**Comment by Groonir** [comment]
It seems that the error comes from the fact that the filetype is not supported. Is it possible to add flac as an option as a feature request?

**Comment by dsymbol** [comment]
clone latest commit and try now should be working.

**Comment by dsymbol** [comment]
clone or git pull latest commit and try should be working.

**Comment by dsymbol** [comment]
clone or git pull latest commit and run from code should be working.

**Comment by Groonir** [comment]
Works well, thanks!
