### ISSUE TITLE
Fetching dependency stuck at 100%

### ISSUE THREAD

**Issue by ThatRandomToast** [dsymbol/yt-dlp-gui#14]
Downloaded from https://github.com/dsymbol/yt-dlp-gui/releases/download/14.05.2023/yt-dlp-gui-win64.zip and yt-dlp-gui.exe keep stuck at 100%.
![image](https://github.com/dsymbol/yt-dlp-gui/assets/75108295/38daac83-2cd6-472f-acb0-98d1f7be98b3)
If I close: 
![image](https://github.com/dsymbol/yt-dlp-gui/assets/75108295/79f2b8ea-6290-40dd-b015-71b9b111c9eb)

OS: Windows 10 Pro for Workstations build 19045.2965

**Comment by dsymbol** [comment]
fixed in 687222a7123b1e2c074b874c8abaa72855872256 run it from [code](https://github.com/dsymbol/yt-dlp-gui#manual) or [build](https://github.com/dsymbol/yt-dlp-gui#build) it.

**Comment by Lum1nial** [comment]
> fixed in [687222a](https://github.com/dsymbol/yt-dlp-gui/commit/687222a7123b1e2c074b874c8abaa72855872256) run it from [code](https://github.com/dsymbol/yt-dlp-gui#manual) or [build](https://github.com/dsymbol/yt-dlp-gui#build) it.

Can you publish it as a download?

**Comment by dsymbol** [comment]
Available now https://github.com/dsymbol/yt-dlp-gui/releases/latest
