### ISSUE TITLE
[Suggestion] Set default settings for custom args and filename

### ISSUE THREAD

**Issue by notBradPitt** [dsymbol/yt-dlp-gui#16]
It'd be nice if custom args and filename doesn't get reset for every download. Would be very useful if for downloading bunch of videos with the same quality and same format and doesn't seem to be difficult to implement. I can make a PR if you're interested in adding this feature

**Comment by dsymbol** [comment]
I'll consider removing https://github.com/dsymbol/yt-dlp-gui/blob/main/app/app.py#L107 - 08 which would stop clearing of custom args and filename after download is added.

**Comment by GabrielOsvair** [comment]
The custom args not being reset every time I open the program, would be great.
