### ISSUE TITLE
GUI uses VP9 instead of AVC now

### ISSUE THREAD

**Issue by KickBoxingBanana** [dsymbol/yt-dlp-gui#19]
The title pretty much says it all but for more details you can see the following conversation.
https://www.reddit.com/r/youtubedl/comments/14kj5h0/ytdlp_gui_suddenly_changed_the_codec_from_avc/

**Comment by dsymbol** [comment]
Done according to multiple ffprobe tests it's back to AVC now, I assume this request is due to vp9 compatibility issues?

**Comment by KickBoxingBanana** [comment]
Indeed,
