### ISSUE TITLE
Get Python error when try to run Windows portable yt-dlp-gui.exe

### ISSUE THREAD

**Issue by akonon** [dsymbol/yt-dlp-gui#20]
Here what I get from the very start of the program:

Traceback (most recent call last):
  File "app.py", line 8, in <module>
ImportError: DLL load failed while importing QtWidgets: The specified procedure could not be found.

**Comment by dsymbol** [comment]
Did you extract all the files beforehand?

**Comment by dsymbol** [comment]
Did you extract all the files and run the exe from the directory its been extracted to?

**Comment by akonon** [comment]
Yes, did exactly like this a few times, no success.

**Comment by dsymbol** [comment]
> Same problem in Windows 8.1 64bit
> 
> ![YT-dlp-gui](https://user-images.githubusercontent.com/142419882/261030782-efd79d6a-6ea8-40c3-98c9-c18b1f449820.png)

Only tested on Windows 10.

> Yes, did exactly like this a few times, no success.

I'm sorry but I cannot reproduce this error, give me some extra details please what OS what yt-dlp-gui version?

**Comment by Paky-ma** [comment]
many thanks for the reply
Yt-dlp-gui last version
The problem is only in Windows 8.1 (tested with two different machine) , in Win 10 works fine

In Windows 8.1 only this old version works

![YT](https://github.com/dsymbol/yt-dlp-gui/assets/142419882/fa42a6d9-738b-4016-83f1-f12c4caed08b)

**Comment by dsymbol** [comment]
> many thanks for the reply Yt-dlp-gui last version The problem is only in Windows 8.1 (tested with two different machine) , in Win 10 works fine
> 
> In Windows 8.1 only this old version works
> 
> ![YT](https://user-images.githubusercontent.com/142419882/261101554-fa42a6d9-738b-4016-83f1-f12c4caed08b.png)

Windows 7 and 8 are no longer supported by Qt6 see https://stackoverflow.com/a/71742165
