### ISSUE TITLE
No handling when module PySide6 not found

### ISSUE THREAD

**Issue by AbdelrhmanUZaki** [dsymbol/yt-dlp-gui#23]
![image](https://github.com/dsymbol/yt-dlp-gui/assets/99971020/790a7985-9d2c-4548-9e19-76c88d4d6094)

**Comment by AbdelrhmanUZaki** [comment]
The erro persists although i download it using
`pip install -r requirements.txt`

**Comment by dsymbol** [comment]
What OS? what python version?
Run `pip freeze` and check that PySide is actually installed.

**Comment by AbdelrhmanUZaki** [comment]
The error was found when I run the exe file, but .py works fine
I'm using win 11
![image](https://github.com/dsymbol/yt-dlp-gui/assets/99971020/4f5b75d9-50b4-4cd5-b7ac-366c6397039a)

**Comment by dsymbol** [comment]
When running the exe you don't need to install requirements / python, simply download the [release](https://github.com/dsymbol/yt-dlp-gui/releases/latest) unzip it and run yt-dlp-gui.exe.
