### ISSUE TITLE
Allow spaces and quotes for Custom Args

### ISSUE THREAD

**Issue by GuyMicciche** [dsymbol/yt-dlp-gui#38]
Allow spaces and quotes for Custom Args:

In `worker.py`, if you change this line (58) from `args += self.cargs.split()` to`args += shlex.split(self.cargs)` Then we can do this:

`--split-chapters -o "chapter:C:\Users\Guy\Downloads\yt-dlp-Downloads\%(title)s\%(section_number)03d. %(section_title)s.%(ext)s"`

Adding quotes and spaces in the names. Because as of now, this is not possible.

Also add `import shlex`

Thank you!

**Comment by dsymbol** [comment]
Done, e081b588527f4c8fef9ddaac11d1c00b919a9608.

About contributor thanks for your offer to help. I appreciate it, but I prefer to keep contributions through pull requests. I also want to maintain a simplistic approach, so I’m avoiding adding too many features. you could always fork and add the features you want.
