### ISSUE TITLE
Chrome thinks your file is sus.

### ISSUE THREAD

**Issue by MagmaBro123** [dsymbol/yt-dlp-gui#40]
Title.

![image](https://github.com/user-attachments/assets/083b3864-5c5c-4d7a-9dcd-58678a3fec66)

(No Issue template is provided don't get mad at me.)

**Comment by dsymbol** [comment]
This program is being built automatically using [actions](https://github.com/dsymbol/yt-dlp-gui/actions), however if you don't trust it you can always upload it to [virustotal](https://www.virustotal.com/gui/home/upload) or build it yourself.

**Comment by dsymbol** [comment]
This program is being built automatically using [actions](https://github.com/dsymbol/yt-dlp-gui/actions), however if you don't trust it you can always build it yourself.
