### ISSUE TITLE
REQ: Please add an option to save m4a audio

### ISSUE THREAD

**Issue by itisljar** [dsymbol/yt-dlp-gui#43]
Hello!

I really like your GUI, it's simple and it works. Personally, I can download m4a version by finding it in yt-dlp console app, but I think there should be an option to download m4a audio only from youtube, as it is present there, just like you have an option for mp3, wav and flac. The problem is, downloading to mp3 means transcoding from lossy to lossy, be it from opus or m4a, and m4a is widely supported on any device now.

...or, some info how to add that myself to GUI, that would be grand.

**Comment by dsymbol** [comment]
Hey please try the latest commit, either [manually](https://github.com/dsymbol/yt-dlp-gui?tab=readme-ov-file#manual) or through [artifact](https://github.com/dsymbol/yt-dlp-gui/actions/runs/11133369091/artifacts/2003031828) refer to [preset-customization](https://github.com/dsymbol/yt-dlp-gui?tab=readme-ov-file#preset-customization) on how to add your own preset.
