### ISSUE TITLE
No opening in Mint 21.3

### ISSUE THREAD

**Issue by colibris79** [dsymbol/yt-dlp-gui#44]
Hi, 
I am using Mint 21.3 (Ubuntu 22.04), Python 3.10.12
Installed following the instructions but when running "python app.py" I get the following:

```
Traceback (most recent call last):
  File "/home/***/yt-dlp-gui/app/app.py", line 10, in <module>
    from worker import Worker
  File "/home/***/yt-dlp-gui/app/worker.py", line 156
    )
    ^
SyntaxError: f-string: expecting '}'
```
Is there anything I can do to solve this?
Thanks

**Comment by dsymbol** [comment]
Could you try the latest commit?

**Comment by colibris79** [comment]
Hi!
Thanks for the fast response. Latest commit and installing libxcb-cursor0 fixed it
