### ISSUE TITLE
request: download only a part of the video

### ISSUE THREAD

**Issue by memebl14** [dsymbol/yt-dlp-gui#46]
it would be nice to be able to download only a part of the video, for example from 5:00 -- 6:30

**Comment by dsymbol** [comment]
can be done using [1](https://github.com/dsymbol/yt-dlp-gui?tab=readme-ov-file#preset-customization) and [2](https://github.com/yt-dlp/yt-dlp/issues/2220#issuecomment-1862933809)

**Comment by memebl14** [comment]
I understand, but it's not as practical as something like this:
![image](https://github.com/user-attachments/assets/367b8fd0-6739-4899-b27d-12a008d13aad)

**Comment by ted-mundy** [comment]
> it's not as practical as something like this:

`--download-sections "*0:600"` works just fine for your example.

**Comment by dsymbol** [comment]
I'm trying to keep the gui simplistic for preset customization, you can look around on github for implementations with more options.
