### ISSUE TITLE
[SUGGESTION] Path selection should default to currently selected path

### ISSUE THREAD

**Issue by athornydevil** [dsymbol/yt-dlp-gui#48]
If I click on the Path ellipsis to choose a new Path, currently the starting point is my default home user path. But if I already have a current Path selected, it would generally be better to start with that Path (as long as it hasn't been deleted). 

For example, I may be downloading all files to an external hard drive, and I'd rather it start there, where I have been downloading to, rather than having to navigate over to that drive every time I select a new path. 

This is analogous to using a text editor like Vim/GVim (also on github), where if I do a File / Open, the starting point is the path where I last opened a file.

**Comment by dsymbol** [comment]
Great idea added in latest commit. 😄
