### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by mikejp56** [dsymbol/yt-dlp-gui#49]
Hi,
I have followed the instructions to download and install yt-dlp-gui, and when I run it I get the error message "Unable to extract uploader id". I am using yt-dlp_linux, and it works fine from the command line.
I have added the debug.log.
Thanks for any help!
[debug.log](https://github.com/user-attachments/files/17685387/debug.log)

**Comment by dsymbol** [comment]
You're using a super old version of yt-dlp (version 2022.04.08) delete it and let yt-dlp-gui download the latest for you. you're getting many HTTP Error 400 probably due to it being outdated.

**Comment by mikejp56** [comment]
Hi dsymbol,
I deleted the yt-dlp-gui folder and reinstalled. I still have an error. I have added the debug log.
Thanks.
[debug.log](https://github.com/user-attachments/files/17689036/debug.log)

**Comment by mikejp56** [comment]
Hi dsymbol,
Sorry I didn't mean to close the issue.

**Comment by mikejp56** [comment]
Hi dsymbol,
The version for yt-dlp is still being reported as 2022.04.08. This is after a new install.

**Comment by mikejp56** [comment]
Hi dsymbol,
I needed to remove the old version with Synaptic. Once I did that the install went smoothly. The installed version is now 2024.11.04, and it works.
I am still fairly new to linux, and kind of feeling my way around things.
Thanks for your patience and feedback.
Regards,
mikejp56

**Comment by mikejp56** [comment]
This issue is now closed.
