### ISSUE TITLE
Suggestion: Download a clip?

### ISSUE THREAD

**Issue by ddubs13** [dsymbol/yt-dlp-gui#5]
To make grabbing clips easier, could you add a feature that grabs a video at a specific timestamp like clipconverter used to do? Or perhaps make it compatible with Youtube's built-in clipping feature?

**Comment by vintprox** [comment]
Here's an example of how to grab just first 10 seconds of the video using commnad line:
```shell
$ yt-dlp --external-downloader ffmpeg --external-downloader-args "ffmpeg_i:-ss 00:00:00.00 -to 00:00:10.00" https://youtu.be/videoId
```

It would be awesome if this tool prospered to open source alternative to Stacher that can get this one single thing right.

Downloading clips by YouTube Clip URLs would be a cherry on top, but not so crucial at that point.
