### ISSUE TITLE
Convert from V9 to H265 if it's not found in the video

### ISSUE THREAD

**Issue by cristalcommons** [dsymbol/yt-dlp-gui#55]
Hello, I can't seem to configure the args to make the conversion from V9 to H265...

```
[presets.Test]
args = [  "-f", "bv*[vcodec~='^(hevc|h265)']+ba/bestvideo+bestaudio", "--recode-video", "mp4", "--postprocessor-args", "-c:v libx265" "-crf 28",]
path = ""
filename = "%(title)s.%(ext)s"
sponsorblock = 0
metadata = false
thumbnail = true
```
I suspect the error is because of the quote symbols in the ```args``` value.

Do you know how to fix this?

Thank you very much for developing this GUI.
Have a nice day.

**Comment by Petrprogs** [comment]
> Hello, I can't seem to configure the args to make the conversion from V9 to H265...
> 
> ```
> [presets.Test]
> args = [  "-f", "bv*[vcodec~='^(hevc|h265)']+ba/bestvideo+bestaudio", "--recode-video", "mp4", "--postprocessor-args", "-c:v libx265" "-crf 28",]
> path = ""
> filename = "%(title)s.%(ext)s"
> sponsorblock = 0
> metadata = false
> thumbnail = true
> ```
> 
> I suspect the error is because of the quote symbols in the `args` value.
> 
> Do you know how to fix this?
> 
> Thank you very much for developing this GUI. Have a nice day.

Hello,
Why do you want to convert VP9 to H265? Maybe just download AVC stream?

**Comment by cristalcommons** [comment]
> Hello, Why do you want to convert VP9 to H265? Maybe just download AVC stream?
Hello, thanks a lot for replying.
I am afraid downloading in h264 is not an option for certain YouTube videos. They will only download in MKV or MP4 with V9 codec, I think.
The goal is downloading some YouTube videos and put them in a Samsung TV. And the codec V9 does not work on that TV, but h265 does for sure.
Before considering YT-DLP presets, I tried to convert the videos using Handbrake and ffmpeg, but the configs I am using tend to make the size much bigger and that's a no-no... Unfortunately, I am totally ignorant about encoding.
After posting, I had been checking the original YT-DLP repository, and it seems other people have the same issue? (https://github.com/yt-dlp/yt-dlp/issues/7607)

**Comment by Petrprogs** [comment]
> > Hello, Why do you want to convert VP9 to H265? Maybe just download AVC stream?
> 
> Hello, thanks a lot for replying. I am afraid downloading in h264 directly is not an option for certain YouTube videos. They will only download in MKV or MP4 with V9 codec, I think. The goal is downloading some YouTube videos and put them in a Samsung TV. And the codec V9 does not work on that TV, but h265 does for sure. Before considering YT-DLP presets, I tried to convert the videos using Handbrake and ffmpeg, but the configs I used made the video file much bigger and that's a no-no... Unfortunately, I am totally ignorant about encoding. After posting, I had been checking the original YT-DLP repository, and it seems other people have the same issue? ([yt-dlp/yt-dlp#7607](https://github.com/yt-dlp/yt-dlp/issues/7607))

I think your TV support AVC codec too, so you can specifiy ```bv[vcodec^=avc]+ba[ext=m4a]``` format. I will download separately AVC video stream and m4a audio stream.
If you really need HEVC (h265), i think this args will be right for you:
```args = [ "-f", "bv[vcodec^=avc]+ba[ext=m4a]", "--exec", "ffmpeg -i {} -c:v libx265 -preset ultrafast {}_HEVC.mp4",]```

**Comment by cristalcommons** [comment]
> I think your TV support AVC codec too, so you can specifiy `bv[vcodec^=avc]+ba[ext=m4a]` format. It will download separately AVC video stream and m4a audio stream and merge them in single mp4. If you really need HEVC (h265), i think this args will be right for you: `args = [ "-f", "bv[vcodec^=avc]+ba[ext=m4a]", "--exec", "ffmpeg -i {} -c:v libx265 -preset ultrafast {}_HEVC.mp4",]`
> 
> Explanation of command: `bv[vcodec^=avc]+ba[ext=m4a]` - get AVC video and M4A audio as separate files and merge them after download `"--exec", "ffmpeg -i {} -c:v libx265 -preset ultrafast {}_HEVC.mp4"` - after downloading and merging, execute ffmpeg to encode video using H265 with ultrafast preset (you should adjust it). File with saved in `name of video_HEVC.mp4`

Aw, thanks so much for writing this for me 🙌 Now it works!

It may be laughable, but after checking the test video files I got thanks to your presets, I think I got it right 1 of the many times I clumsily tried. I was using "-c:v libx265" for sure. But I wasn't quite sure that the codec was ‘pure h264/5’, so I kept trying other settings and then messed with the args xD. Now, with your config, I see that it is the same codec.

Thank you very much, I will use the configs you made and try to download the videos now. Finally, yay.

**Comment by Petrprogs** [comment]
I was glad to help you. Don't forget to close issue 😉

**Comment by Petrprogs** [comment]
> > I think your TV support AVC codec too, so you can specifiy `bv[vcodec^=avc]+ba[ext=m4a]` format. It will download separately AVC video stream and m4a audio stream and merge them in single mp4. If you really need HEVC (h265), i think this args will be right for you: `args = [ "-f", "bv[vcodec^=avc]+ba[ext=m4a]", "--exec", "ffmpeg -i {} -c:v libx265 -preset ultrafast {}_HEVC.mp4",]`
> > Explanation of command: `bv[vcodec^=avc]+ba[ext=m4a]` - get AVC video and M4A audio as separate files and merge them after download `"--exec", "ffmpeg -i {} -c:v libx265 -preset ultrafast {}_HEVC.mp4"` - after downloading and merging, execute ffmpeg to encode video using H265 with ultrafast preset (you should adjust it). File with saved in `name of video_HEVC.mp4`
> 
> Aw, thanks so much for writing this for me 🙌 Now it works!
> 
> It may be laughable, but after checking the test video files I got thanks to your presets, I think I got it right 1 of the many times I clumsily tried. I was using "-c:v libx265" for sure. But I wasn't quite sure that the codec was ‘pure h264/5’, so I kept trying other settings and then messed with the args xD. Now, with your config, I see that it is the same codec.
> 
> Thank you very much, I will use the configs you made and try to download the videos now. Finally, yay.

I was glad to help you! Don't forget to close the issue 😉
