### ISSUE TITLE
[Feature Request] Be Able To Rename The Output File During Conversion 

### ISSUE THREAD

**Issue by TheNightRider12** [dsymbol/yt-dlp-gui#7]
With yt-dlp using the command line, you can use the -o argument to specify the output file name.
Example: `yt-dlp https://www.youtube.com/watch?v=n_uFzLPYDd8 -o "Jazz Example.mp3"` and the output file would be named "Jazz Example.mp3". I know for some sites that I download from, the file name is random. It would be cool if I could specify the file name that I want and have it be done during the downloading and conversion process.

**Comment by KuMinh4T** [comment]
Can you add Progressbar in the treewidget to make it look better? If you have time please update . Thanks if you update
